# Generated by Django 3.0.8 on 2020-07-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TC', 'Technology'), ('CR', 'Curiosity'), ('GR', 'Geral')], default='GR', max_length=2),
        ),
    ]
